fix(lib): expose testing matchers for other languages properly
hashicorp/terraform-cdk pull request #1006
Opened 2021-09-11 08:40 UTC by DanielMSchmidt

2021-09-12 03:18 UTC, jsteinich commented on packages/cdktf/lib/testing/matchers.ts
>  export type MatcherReturn = { message: () => string; pass: boolean };
I'm pretty sure this won't work with jsii

2021-09-12 03:18 UTC, jsteinich commented on packages/cdktf/lib/testing/matchers.ts
> +    properties?: Record<string, any>
I think I came across any issue related to and optional record type in jsii. Just using a string keyed map may be needed instead.

2021-09-15 03:04 UTC, jsteinich requested changes
It's getting closer, but still some issues.
I only checked Java, but problems that I saw:

- `TerraformConstructor` doesn't work as intended. In native Java, the parameter would end up being `Class<? extends ITerraformResource>` or `Class<T> T extends ITerraformResource`. Neither of those are representable with jsii to my knowledge. C# would be similar.
- `IScopeCallback` also doesn't translate via jsii. [jsii callbacks](https://aws.github.io/jsii/user-guides/language-support/callbacks/) might work, but it might be better to just expose a method to get a testing stack.

I expect the jsii issues will cause issues across all the other non ts/js languages as well.

2021-09-15 08:20 UTC, ansgarm approved these changes

2021-12-01 15:27 UTC, closed without merging