feat(cli): Support nested_type in generator
hashicorp/terraform-cdk pull request #1630
Opened 2022-03-19 12:04 UTC by jsteinich

Support for tfproto v6
Fixes #1397

2022-03-24 02:09 UTC, jsteinich commented
This does break compatibility in that the new cli will generate binding not compatible with the old cdktf lib since the order of parameters was changed in `ComplexObject` constructor.
Technically some minor breaking changes as well. Mostly this helps the user by returning more information for nested computed lists. For nested computed maps it's maybe worse (`getStringMapAttribute` -> `StringMap.lookup`). We had already planned on making some changes there, so I may just follow this up with that work.

I've looked quite a bit at how this changes existing providers and also confirmed that providers using the new protocol successfully build. Could probably use some tests to confirm that synth works correctly with nested types.

2022-03-25 15:02 UTC, jsteinich commented on packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap
> +export function awsProviderAssumeRoleToTerraform(struct?: AwsProviderAssumeRole): any {
This wasn't an intentional change, but it didn't seem to break any tests so I hadn't looked into it. I'll do some more digging to see why it changed.

Adding `IResolvable` to these functions was done to make sure things that can't be represented by tokens natively wouldn't break.

2022-03-25 15:05 UTC, jsteinich commented on packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts
> +        `super(terraformResource, terraformAttribute, complexObjectIsFromSet, complexObjectKey);`
Good catch. I'll fix.

2022-03-25 15:11 UTC, ansgarm commented on packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap
> +export function awsProviderAssumeRoleToTerraform(struct?: AwsProviderAssumeRole): any {
I think it'll probably be fine :)

2022-03-25 15:38 UTC, ansgarm approved these changes

2022-03-28 17:17 UTC, jsteinich commented on packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap
> +export function awsProviderAssumeRoleToTerraform(struct?: AwsProviderAssumeRole): any {
There was a missing case for single item sets in resource-parser. I had forgotten adding that in.
The `IResolvable` is only needed for a [specific case](https://github.com/hashicorp/terraform-cdk/blob/f97577c4b91833771665be3b0672492cf9bccbea/packages/%40cdktf/provider-generator/lib/get/generator/models/attribute-type-model.ts#L110), so removing this is completely fine.

2022-03-29 09:40 UTC, ansgarm requested changes
I just tested this with the `awscc` provider and there seems to be an issue with invalid TypeScript code created for datasources:
```
// throttle - computed: true, optional: false, required: false
  private _throttle = new { [key: string]: DataAwsccApigatewayUsagePlanApiStagesThrottle } | cdktf.IResolvableMap(this, "throttle");
  public get throttle() {
    return this._throttle;
  }
```
(`"hashicorp/awscc@~> 0.16.0"`; `.gen/providers/awscc/data-awscc-apigateway-usage-plan.ts`)

The TS errors are:
> This expression is not constructable.
>  Type '{ [x: number]: any; DataAwsccApigatewayUsagePlanApiStagesThrottle: any; }' has no construct signatures.

> Property 'IResolvableMap' does not exist on type 'typeof import("/Users/ansgar/projects/playground/test-get-awscc/node_modules/cdktf/lib/index")'.

2022-03-29 13:44 UTC, ansgarm approved these changes
Really cool @jsteinich 👍

2022-03-29 15:03 UTC, merged