chore(docs): translate all the code samples
hashicorp/terraform-cdk pull request #1931
Opened 2022-07-18 12:07 UTC by DanielMSchmidt

Closes #1929

2022-07-18 13:54 UTC, BRKalow commented on website/docs/cdktf/concepts/constructs.mdx
>  ```ts
```suggestion
<CodeTabs>

```ts
```

2022-07-20 16:24 UTC, ansgarm requested changes

2022-07-20 16:24 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +```
intentional?

2022-07-20 16:24 UTC, ansgarm commented on website/docs/cdktf/create-and-deploy/best-practices.mdx
> +new Blog(app, "ecommerce-development", new BlogProps {
Those two constructs have the same name which should fail, shouldn't it?
I think another Blog construct further down is also called "ecommerce" in its it as well.

Also true for other languages.

2022-07-21 09:26 UTC, ansgarm requested changes
I think we should test the Go code that's in the examples as it is still containing some errors

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/assets.mdx
> +	asset := cdktf.NewTerraformAsset(this, jsii.String("lambda-asset"), &terraformAssetConfig{
This also needs to be `&cdktf.TerraformAssetConfig{`

Maybe testing the snippets will find more errors as I'm a bad Go compiler and there could be more missing.

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/assets.mdx
> +app.synth()
```suggestion
app.Synth()
```

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +app.synth()
also needs a capital `S`

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +func newPublicS3Bucket(scope construct, name *string) *publicS3Bucket {
```suggestion
func NewPublicS3Bucket(scope construct, name *string) *publicS3Bucket {
```

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +	newTerraformStack_Override(this, scope, name)
```suggestion
	NewTerraformStack_Override(this, scope, name)
```

2022-07-21 09:26 UTC, ansgarm commented on website/docs/cdktf/concepts/data-sources.mdx
> +	cdktf.NewTerraformOutput(this, jsii.String("region"), &terraformOutputConfig{
```suggestion
	cdktf.NewTerraformOutput(this, jsii.String("region"), &cdktf.TerraformOutputConfig{
```

2022-07-21 10:12 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +  }
indentation seems off

2022-07-21 10:12 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +	construct
I think this needs a type
```suggestion
	construct constructs.Construct
```

2022-07-21 10:12 UTC, ansgarm commented on website/docs/cdktf/concepts/constructs.mdx
> +	bucket s3Bucket
requires the namespace I think, possibly needs to be `myconstructs.S3Bucket`?

2022-07-23 03:49 UTC, jsteinich requested changes
Just scanning through I can see a handful of issues:

- Some current directory lookup errors
- `Map.of`/`List.of` Java issues

There are probably other issues as jsii isn't perfect at translating. Most sure why to find them all would be to synth each example and compare.

2022-08-12 14:11 UTC, closed without merging