refactor(cli): move cli library into seperate package
hashicorp/terraform-cdk pull request #2253
Opened 2022-11-04 13:32 UTC by DanielMSchmidt

This allows us to build another package that wraps the CLI implementation package
into a JSII compatible layer without restricting our usage to JSII compatible TS.

2022-11-06 19:11 UTC, jsteinich commented
Is there a list of the desired divisions? Goals for the different parts? It's important to really plan out this type of refactoring so it doesn't just end up as a mess.

2022-11-07 10:20 UTC, DanielMSchmidt commented
@jsteinich Please treat this more as an experiment for now :) I'm trying to see how we can move all functionality in one package that is consumed by the CLI as a first step. This iteration would not contain the goal to publish a usable API for folks, but to bundle all dependencies / actual work being done in a sub-package. This sub-package can then be used in the next step by a different package that can do the JSII interface on top of it (and ship this package as a bundled dependency), so that we don't need to use the JSII interface internally. That being said, I'm starting a second PR to envision how the JSII API shall look like, I'll share this one when that's in a better state then hello world :D

2022-11-18 10:55 UTC, ansgarm requested changes
Nice work! I really like the introduction of the `commons` package, too ❤️

The only main thing that I'd require is to address the added ambiguity for users which is having both a `@cdktf/cli` and a `cdktf-cli` package. I'd prefer to rename the new package but if you want to keep the `@cdktf/cli` name (which I could understand, too) the bare minimum to me would be to have some kind of warning printed when that package is installed globally accidentally:
```
npm i -g @cdktf/cli
...
Warning: You might be looking for cdktf-cli! @cdktf/cli is an internal package used to power the commands in the cdkt-cli
```
~ something like that

2022-11-18 10:55 UTC, ansgarm commented on packages/@cdktf/cli/src/lib/index.ts
> +// Convert is not included here since it's published independently as @cdktf/hcl2cdk.
This should go in the Readme of the package, too 😁

2022-11-21 13:31 UTC, ansgarm approved these changes
<img src="https://media1.giphy.com/media/lALXmzceZjqI1ogAYQ/giphy.gif"/>

2022-11-21 13:31 UTC, ansgarm commented on packages/@cdktf/commons/README.md
> +This package is meant to contain all code shared across the packages, like logging, types, configuraion, etc. It is not meant for public usage and will not have a stable API.
```suggestion
This package is meant to contain all code shared across the packages, like logging, types, configuration, etc. It is not meant for public usage and will not have a stable API.
```

2022-11-21 13:54 UTC, merged