jsii 5
hashicorp/terraform-cdk pull request #2776
Opened 2023-04-05 15:54 UTC by DanielMSchmidt

- chore(lib): update to JSII 5
- chore: update snapshots to the jest 29 format

2023-04-05 15:55 UTC, team-tf-cdk commented
This PR exceeds the recommended size of 1000 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.

2023-04-05 16:50 UTC, team-tf-cdk commented
This PR exceeds the recommended size of 1000 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.

2023-04-06 07:10 UTC, ansgarm requested changes
Nice work! Only two simple blockers (two rewritten tests have a tiny oversight that makes them more flaky) – the only reason why I didn't approve 😄

2023-04-06 07:10 UTC, ansgarm commented on packages/@cdktf/hcl2cdk/lib/iteration.ts
> +      ...items.reduce((innerCarry, item: T) => {
ah, nice 👏

2023-04-06 07:10 UTC, ansgarm commented on packages/@cdktf/hcl2json/test/hcl2json.test.ts
> +    expect(
(Blocker)
Mutahhir just recently fixed some tests by returning the result from `expect(...).rejects|resolves` – I think we need to do this here, too.

Related docs: https://jestjs.io/docs/asynchronous#resolves--rejects

2023-04-06 07:10 UTC, ansgarm commented on packages/@cdktf/hcl2json/test/hcl2json.test.ts
> +    expect(convertFiles(path.join("/some/not/existing/path"))).rejects.toMatch(
(Blocker)
[same here](https://jestjs.io/docs/asynchronous#resolves--rejects)

2023-04-06 07:28 UTC, DanielMSchmidt commented on packages/@cdktf/cli-core/package.json
> +    "jsii-pacmak": "^1.79.0",
I think whatever is available, afaik. there is no newer version released

2023-04-06 07:32 UTC, team-tf-cdk commented
This PR exceeds the recommended size of 1000 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.

2023-04-06 08:49 UTC, team-tf-cdk commented
This PR exceeds the recommended size of 1000 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.

2023-04-06 08:57 UTC, team-tf-cdk commented
This PR exceeds the recommended size of 1000 lines. Please make sure you are NOT addressing multiple issues with one PR. Note this PR might be rejected due to its size.

2023-04-06 10:52 UTC, ansgarm approved these changes
<img src="https://media3.giphy.com/media/111ebonMs90YLu/giphy.gif"/>

2023-04-06 11:27 UTC, merged