chore: Try out tsx instead of ts-node
hashicorp/terraform-cdk pull request #2857
Opened 2023-05-04 08:31 UTC by mutahhir

### Related issue

Fixes # 

### Description

In plain English, describe your approach to addressing the issue linked above. For example, if you made a particular design decision, let us know why you chose this path instead of another solution.

### Checklist

- [ ] I have updated the PR title to match [CDKTF's style guide](https://github.com/hashicorp/terraform-cdk/blob/main/CONTRIBUTING.md#pull-requests-1)
- [ ] I have run the linter on my code locally
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation if applicable
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works if applicable
- [ ] New and existing unit tests pass locally with my changes

2023-05-08 08:14 UTC, ansgarm reviewed
In general I'm in favor of switching to `tsx`, however `esbuild` is not a drop in replacement for TypeScript (e.g. it doesn't implement its type system which means it does not type check the code, [docs](https://esbuild.github.io/content-types/#typescript)) which might have some implications / drawbacks that we didn't think about yet.

2023-06-01 09:40 UTC, DanielMSchmidt requested changes
Let's not do the template yet, maybe we can add the examples as well

2023-06-05 13:42 UTC, DanielMSchmidt approved these changes

2023-08-07 09:59 UTC, ansgarm commented
I did look into this some more and it seems that 60s synth times happen when TypeScript projects use star imports (could you confirm whether this is the case for your large project, @mutahhir?).

The same 60s synth project went down to a few seconds after changing the imports to specific ones. I'll create a PR to do this in our examples (e.g. the `aws-prebuilt` example uses a star import).

That said, I would say improving this would be an documentation exercise, possibly paired with some help our tooling:
One quick idea would be to set `global.CDKTF_STAR_IMPORT_USED = true` in the `index.ts` of provider bindings. We could then check whether this global is `true` during synth and print a warning (e.g. if synth takes longer than e.g. 15s) which could link to some new docs detailing how to improve TypeScript performance.

Furthermore, we could also opt-out of type checking by passing the `-T` flag or the `--swc` flag to `ts-node` which both will speed up the synth time (With `swc`, which is similar to `esbuild`, my 60s example took 10s [while keeping the slow star import]). Both these options are something we could document.

If we want type checking and faster builds on subsequent runs, we'd probably have to switch back to `tsc` as `ts-node` doesn't support any caching.

One other alternative to mention: @DanielMSchmidt has done some discovery on using an `index-lazy.ts` file, I think it was specifically for improving the performance of JSII enabled languages by loading less code into Node.js, and trying this locally in TypeScript also gave me drastic improvements in performance which came close to the non-star-imports. Type information get's lost when doing these `Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });` definitions, so we'd have to generate some `.d.ts` file probably.
This might be the best way forward, but might carry more work and problems with possible incompatibilities (i.e. some users use Webpack or other tools to compile their CDKTF projects).

2023-09-01 08:47 UTC, closed without merging