fix: do not always overwrite global.performance
hashicorp/terraform-cdk pull request #2922
Opened 2023-06-08 06:29 UTC by robertkowalski

new node version already have a performance global, see https://nodejs.org/api/globals.html#performance

it contains many methods, see https://nodejs.org/api/perf_hooks.html

when always overwriting it, other modules like `undici` which use the performance object won't work any more. in genera using the performance object become unusable as soon as the `@cdktf/hcl2json` package is required.

discussion/bug: https://github.com/renovatebot/renovate/discussions/22615

### Related issue

Fixes # 

### Description

In plain English, describe your approach to addressing the issue linked above. For example, if you made a particular design decision, let us know why you chose this path instead of another solution.

### Checklist

- [ ] I have updated the PR title to match [CDKTF's style guide](https://github.com/hashicorp/terraform-cdk/blob/main/CONTRIBUTING.md#pull-requests-1)
- [x] I have run the linter on my code locally
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if applicable
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works if applicable
- [ ] New and existing unit tests pass locally with my changes

2023-06-08 06:29 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=2922)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=2922)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-cdk?pullRequest=2922).</sub>

2023-06-08 11:33 UTC, robertkowalski commented
I forked the repository to run all the unit tests

2023-06-08 11:33 UTC, robertkowalski commented
<img width="826" alt="Screenshot 2023-06-08 at 13 33 29" src="https://github.com/hashicorp/terraform-cdk/assets/298166/2f38ddc3-b9b2-4d26-a5da-6ba07eaca57b">

2023-06-09 07:47 UTC, mutahhir requested changes
Thank you for the contribution!! 

As mentioned in the header of this file (wasm_bridge_exec), we tend to follow Golang's `wasm_exec_node`. Can you update the PR to match that (specifically [this](https://github.com/golang/go/blob/master/misc/wasm/wasm_exec_node.js#L12-L19))?

2023-06-09 09:11 UTC, robertkowalski commented
@mutahhir updated and adjusted the commit message

2023-06-12 06:40 UTC, robertkowalski commented
@mutahhir with the changes to crypto unit tests fail, i will revert the changes for crypto

```
$ node ./lib/__tests__/edge-provider-schema/cli.js ./edge-provider-bindings
/__w/terraform-cdk/terraform-cdk/packages/@cdktf/hcl2json/wasm/wasm_exec.js:288
						crypto.getRandomValues(loadSlice(sp + 8));
						       ^

TypeError: crypto.getRandomValues is not a function
```

2023-06-12 06:52 UTC, mutahhir approved these changes
Nice! Thank you! 🏅

2023-06-16 08:06 UTC, merged