Increase Maven max memory
hashicorp/terraform-cdk pull request #380
Opened 2020-09-22 13:02 UTC by jsteinich

The jsii/superchain image sets `MAVEN_OPTS` with a max heap size that is too small for generating some of the larger providers. I've worked around it in #360, but for https://github.com/terraform-cdk-providers/cdktf-provider-project/pull/14 it will be easier to just have the value increased.

2020-09-22 13:04 UTC, jsteinich commented
When building the docker image locally I'm getting:
```
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
```

I'll try to look into it more later, but we may want to be a bit more explicit with base image version and pipenv install script version.

2020-09-23 12:52 UTC, jsteinich commented
Switching to python3 for the pip install fixed it.

2020-09-23 18:10 UTC, skorfmann commented
We can merge this, but we still don't have automatically docker builds /cc @anubhavmishra

2020-09-23 18:11 UTC, skorfmann approved these changes

2020-09-23 18:50 UTC, anubhavmishra requested changes

2020-09-23 18:50 UTC, anubhavmishra commented on Dockerfile
> +    MAVEN_OPTS="-Xms256m -Xmx3G"
@jsteinich can add a comment about the maven option being set?

2020-09-24 20:06 UTC, anubhavmishra approved these changes

2020-10-05 09:33 UTC, skorfmann commented
Merging, will be published manually or via #396

2020-10-05 09:34 UTC, merged