Add prerequisites to contributing docs
hashicorp/terraform-cdk pull request #665
Opened 2021-04-28 22:45 UTC by DanielMSchmidt

While setting up the project I found these dependencies to the development machine to exist :)

2021-04-28 22:45 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=665)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-cdk?pullRequest=665)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-cdk?pullRequest=665).</sub>

2021-04-28 22:46 UTC, danieldreier commented
👋 welcome!

2021-04-29 12:33 UTC, jsteinich commented
We should probably mention the docker image that has all the dependencies bundled: `hashicorp.jfrog.io/docker/hashicorp/jsii-terraform` (Dockerfile in the repo)

2021-04-29 15:05 UTC, DanielMSchmidt commented
That sounds like a great idea, maybe adding a wrapper shell script could help folks, like `./docker.sh package`, `./docker.sh integration`, etc

2021-04-30 16:12 UTC, DanielMSchmidt commented
@jsteinich Great point, didn't notice the dockerfile previously. I added a note about it as well as the vscode dev containers so folks can choose :)

2021-04-30 19:54 UTC, jsteinich requested changes
Looks good besides a small accidental change.

2021-04-30 19:54 UTC, jsteinich commented on CONTRIBUTING.md
> -#### C#
Shouldn't remove this.

2021-05-03 01:33 UTC, jsteinich approved these changes

2021-05-03 07:10 UTC, merged